### PR TITLE
Fix/anyblock sunset

### PR DESCRIPTION
**Pull request by sascha-blockdaemon**
Remove Anyblock AMPL VWAP Endpoint & update gasprice endpoint to use Blockdaemon API instead

### CODE REVIEW

**Comment by austinborn** [comment]
FYI you can ignore the soak tests, since these do not run for PRs from forked branches.

**Comment by austinborn** [comment]
Great, just 2 things to change:
1. One unit test is failing now since you removed some of the input parameters. Can you remove that specific test from `gasprice.test.ts`:
```
FAIL packages/sources/anyblock/test/unit/gasprice.test.ts (6.493 s)
  ● execute › validation error › empty body

    expect(received).toEqual(expected) // deep equality

    Expected: 400
    Received: 200

       5 |
       6 | export function assertError(statusCode: any, data: any, expectedJobId: any) {
    >  7 |   expect(statusCode.actual).toEqual(statusCode.expected)
         |                             ^
       8 |   expect(data.jobRunID).toEqual(expectedJobId)
       9 |   expect(data.status).toEqual('errored')
      10 |   expect(data.error).toBeTruthy()

      at assertError (packages/core/test-helpers/src/helpers.ts:7:29)
      at Object.<anonymous> (packages/sources/anyblock/test/unit/gasprice.test.ts:25:11)
```
2. Can you run `yarn && yarn setup && yarn changeset` in the root directory and follow the steps [here](https://github.com/smartcontractkit/external-adapters-js/blob/develop/CONTRIBUTING.md#generating-changesets) to add a changeset file? This allows our automation to handle upgrading versions for release.

**Comment by austinborn** [comment]
And since this is represents a large breaking change, I would select `Major` for the changeset level.

**Comment by sascha-blockdaemon** [comment]
@austinborn Removed the unit test completely, since the broken one was the only remaining test.
Changeset added & merged latest upstream changes.

**Review by austinborn — APPROVED** [review]

**Pull request merged**
