### PR TITLE
Adding MIM override

### PR DESCRIPTION
**Pull request by nikhsha**
## Description

......

## Changes

added a single line overriding a new token

## Steps to Test

none

## Quality Assurance

- [ ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `<ADAPTER_PACKAGE>/schemas/env.json` and `<ADAPTER_PACKAGE>/README.md`
- [ ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `infra-k8s` configuration file.
- [ ] The branch naming follows git flow (`feature/x`, `chore/x`, `release/x`, `hotfix/x`, `fix/x`) or is created from Clubhouse/Shortcut
- [ ] This is related to a maximum of one Clubhouse/Shortcut story or GitHub issue
- [ ] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)
- [ ] All code changes have 100% unit and integration test coverage. If testing is not applicable or too difficult to justify doing, the reasoning should be documented explicitly in the PR.

### CODE REVIEW

**Comment by cl-ea-js-service** [comment]
<details><summary>:heavy_check_mark: Soak test for coinmarketcap succeeded</summary>

```

running (09m45.7s), 1/1 VUs, 111 complete and 0 interrupted iterations
default   [  97% ] 1 VUs  09m44.5s/10m0s

running (09m46.7s), 1/1 VUs, 111 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m45.5s/10m0s

running (09m47.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.5s/10m0s

running (09m48.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.5s/10m0s

running (09m49.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.5s/10m0s

running (09m50.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.5s/10m0s

running (09m51.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.5s/10m0s

running (09m52.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.5s/10m0s

running (09m53.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.5s/10m0s

running (09m54.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.5s/10m0s

running (09m55.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.5s/10m0s

running (09m56.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.5s/10m0s

running (09m57.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.5s/10m0s

running (09m58.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.5s/10m0s

running (09m59.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.5s/10m0s

running (10m00.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.5s/10m0s

running (10m01.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.7s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

running (10m03.7s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✗ Group-coinmarketcap-BAND / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-BNB / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-ALCX / USD returned 200
      ↳  97% — ✓ 112 / ✗ 3
     ✗ Group-coinmarketcap-ANT / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-CREAM / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✓ Group-coinmarketcap-BAL / ETH returned 200
     ✓ Group-coinmarketcap-BUSD / USD returned 200
     ✓ Group-coinmarketcap-BOND / ETH returned 200
     ✓ Group-coinmarketcap-CRO / ETH returned 200
     ✗ Group-coinmarketcap-AVAX / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-BIT / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-BTC / USD returned 200
      ↳  97% — ✓ 112 / ✗ 3
     ✗ Group-coinmarketcap-AXS / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-BORING / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✓ Group-coinmarketcap-ANKR / USD returned 200
     ✗ Group-coinmarketcap-ATOM / ETH returned 200
      ↳  96% — ✓ 111 / ✗ 4
     ✗ Group-coinmarketcap-AMP / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-BNB / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-AMPL / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-AMPL / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✓ Group-coinmarketcap-BTC / ETH returned 200
     ✗ Group-coinmarketcap-AUDIO / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✓ Group-coinmarketcap-C98 / USD returned 200
     ✓ Group-coinmarketcap-ATOM / USD returned 200
     ✓ Group-coinmarketcap-ADA / USD returned 200
     ✓ Group-coinmarketcap-ALPHA / ETH returned 200
     ✓ Group-coinmarketcap-ARPA / USD returned 200
     ✓ Group-coinmarketcap-COMP / ETH returned 200
     ✗ Group-coinmarketcap-BAND / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-COMP / USD returned 200
      ↳  97% — ✓ 112 / ✗ 3
     ✓ Group-coinmarketcap-ADX / USD returned 200
     ✗ Group-coinmarketcap-CELO / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✓ Group-coinmarketcap-BAT / ETH returned 200
     ✓ Group-coinmarketcap-CAKE / USD returned 200
     ✓ Group-coinmarketcap-APE / USD returned 200
     ✓ Group-coinmarketcap-BNT / ETH returned 200
     ✓ Group-coinmarketcap-1INCH / ETH returned 200
     ✓ Group-coinmarketcap-AAVE / ETH returned 200
     ✓ Group-coinmarketcap-ALUSD / USD returned 200
     ✓ Group-coinmarketcap-BADGER / USD returned 200
     ✓ Group-coinmarketcap-ALBT / USD returned 200
     ✓ Group-coinmarketcap-BADGER / ETH returned 200
     ✗ Group-coinmarketcap-BAL / USD returned 200
      ↳  96% — ✓ 111 / ✗ 4
     ✗ Group-coinmarketcap-AAVE / USD returned 200
      ↳  96% — ✓ 111 / ✗ 4
     ✓ Group-coinmarketcap-CEL / ETH returned 200
     ✓ Group-coinmarketcap-ALCX / ETH returned 200
     ✓ Group-coinmarketcap-1INCH / USD returned 200
     ✓ Group-coinmarketcap-BNT / USD returned 200
     ✓ Group-coinmarketcap-BUSD / ETH returned 200
     ✗ Group-coinmarketcap-APE / ETH returned 200
      ↳  96% — ✓ 111 / ✗ 4

     checks.........................: 97.73% ✓ 5620     ✗ 130 
     data_received..................: 1.7 MB 2.8 kB/s
     data_sent......................: 787 kB 1.3 kB/s
     errors.........................: 2.26%  ✓ 130      ✗ 5620
     http_req_blocked...............: avg=37.39µs min=106ns   med=236ns   max=212.49ms p(90)=360ns    p(95)=501ns   
     http_req_connecting............: avg=50ns    min=0s      med=0s      max=291.86µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=68.18ms min=4.64ms  med=12.47ms max=3.66s    p(90)=16.65ms  p(95)=19.91ms 
       { expected_response:true }...: avg=21.37ms min=4.64ms  med=12.43ms max=3.66s    p(90)=16.05ms  p(95)=18.24ms 
   ✓ http_req_failed................: 2.26%  ✓ 130      ✗ 5620
     http_req_receiving.............: avg=73.94µs min=11.12µs med=47.43µs max=14.27ms  p(90)=102.9µs  p(95)=126.19µs
     http_req_sending...............: avg=65.07µs min=12.12µs med=44.89µs max=519.61µs p(90)=126.34µs p(95)=205.32µs
     http_req_tls_handshaking.......: avg=19.68µs min=0s      med=0s      max=113.2ms  p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=68.04ms min=4.56ms  med=12.35ms max=3.66s    p(90)=16.43ms  p(95)=19.62ms 
     http_reqs......................: 5750   9.524604/s
     iteration_duration.............: avg=5.22s   min=4.99s   med=5s      max=10.11s   p(90)=5s       p(95)=7.57s   
     iterations.....................: 115    0.190492/s
     vus............................: 0      min=0      max=1 
     vus_max........................: 1      min=0      max=1 
```
</details>

**Review by ainsleybc — DISMISSED** [review]

**Comment by cl-ea-js-service** [comment]
<details><summary>:heavy_check_mark: Soak test for coinmarketcap succeeded</summary>

```
default   [  98% ] 1 VUs  09m46.3s/10m0s

running (09m48.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.3s/10m0s

running (09m49.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.3s/10m0s

running (09m50.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.3s/10m0s

running (09m51.7s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.3s/10m0s

running (09m52.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.3s/10m0s

running (09m53.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.3s/10m0s

running (09m54.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.3s/10m0s

running (09m55.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.3s/10m0s

running (09m56.7s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.3s/10m0s

running (09m57.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.3s/10m0s

running (09m58.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.3s/10m0s

running (09m59.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.3s/10m0s

running (10m00.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.3s/10m0s

running (10m01.7s), 1/1 VUs, 114 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.7s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

running (10m03.7s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

running (10m03.8s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✓ Group-coinmarketcap-BNT / ETH returned 200
     ✓ Group-coinmarketcap-BADGER / ETH returned 200
     ✗ Group-coinmarketcap-AXS / ETH returned 200
      ↳  98% — ✓ 113 / ✗ 2
     ✗ Group-coinmarketcap-ALCX / USD returned 200
      ↳  97% — ✓ 112 / ✗ 3
     ✗ Group-coinmarketcap-APE / ETH returned 200
      ↳  96% — ✓ 111 / ✗ 4
     ✗ Group-coinmarketcap-1INCH / ETH returned 200
      ↳  96% — ✓ 111 / ✗ 4
     ✗ Group-coinmarketcap-ADA / USD returned 200
      ↳  93% — ✓ 107 / ✗ 8
     ✓ Group-coinmarketcap-BAL / ETH returned 200
     ✗ Group-coinmarketcap-CRO / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-ALUSD / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-ATOM / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-COMP / ETH returned 200
      ↳  97% — ✓ 112 / ✗ 3
     ✗ Group-coinmarketcap-CELO / ETH returned 200
      ↳  93% — ✓ 107 / ✗ 8
     ✓ Group-coinmarketcap-ARPA / USD returned 200
     ✓ Group-coinmarketcap-BAND / ETH returned 200
     ✓ Group-coinmarketcap-BAND / USD returned 200
     ✗ Group-coinmarketcap-AVAX / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✓ Group-coinmarketcap-BNB / USD returned 200
     ✓ Group-coinmarketcap-ADX / USD returned 200
     ✓ Group-coinmarketcap-1INCH / USD returned 200
     ✓ Group-coinmarketcap-BIT / USD returned 200
     ✗ Group-coinmarketcap-C98 / USD returned 200
      ↳  92% — ✓ 106 / ✗ 9
     ✗ Group-coinmarketcap-ATOM / USD returned 200
      ↳  93% — ✓ 107 / ✗ 8
     ✗ Group-coinmarketcap-BAL / USD returned 200
      ↳  97% — ✓ 112 / ✗ 3
     ✗ Group-coinmarketcap-AAVE / USD returned 200
      ↳  96% — ✓ 111 / ✗ 4
     ✓ Group-coinmarketcap-BORING / USD returned 200
     ✓ Group-coinmarketcap-ALBT / USD returned 200
     ✓ Group-coinmarketcap-COMP / USD returned 200
     ✓ Group-coinmarketcap-BUSD / USD returned 200
     ✓ Group-coinmarketcap-APE / USD returned 200
     ✗ Group-coinmarketcap-BTC / USD returned 200
      ↳  96% — ✓ 111 / ✗ 4
     ✗ Group-coinmarketcap-ANT / ETH returned 200
      ↳  93% — ✓ 107 / ✗ 8
     ✗ Group-coinmarketcap-AMPL / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✓ Group-coinmarketcap-BTC / ETH returned 200
     ✗ Group-coinmarketcap-CREAM / ETH returned 200
      ↳  93% — ✓ 107 / ✗ 8
     ✗ Group-coinmarketcap-BOND / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✓ Group-coinmarketcap-AMPL / ETH returned 200
     ✓ Group-coinmarketcap-BAT / ETH returned 200
     ✓ Group-coinmarketcap-CEL / ETH returned 200
     ✓ Group-coinmarketcap-AAVE / ETH returned 200
     ✗ Group-coinmarketcap-AUDIO / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✓ Group-coinmarketcap-BADGER / USD returned 200
     ✓ Group-coinmarketcap-BNB / ETH returned 200
     ✗ Group-coinmarketcap-ANKR / USD returned 200
      ↳  93% — ✓ 107 / ✗ 8
     ✗ Group-coinmarketcap-AMP / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinmarketcap-BNT / USD returned 200
      ↳  96% — ✓ 111 / ✗ 4
     ✗ Group-coinmarketcap-ALPHA / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-ALCX / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinmarketcap-CAKE / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✓ Group-coinmarketcap-BUSD / ETH returned 200

     checks.........................: 97.54% ✓ 5609     ✗ 141 
     data_received..................: 1.7 MB 2.8 kB/s
     data_sent......................: 787 kB 1.3 kB/s
     errors.........................: 2.45%  ✓ 141      ✗ 5609
     http_req_blocked...............: avg=34.55µs min=105ns   med=201ns   max=196.67ms p(90)=311ns    p(95)=414ns   
     http_req_connecting............: avg=122ns   min=0s      med=0s      max=704.04µs p(90)=0s       p(95)=0s      
   ✓ http_req_duration..............: avg=70.03ms min=2.43ms  med=13.25ms max=4.78s    p(90)=17.59ms  p(95)=20.98ms 
       { expected_response:true }...: avg=22.44ms min=4.32ms  med=13.2ms  max=4.78s    p(90)=17.05ms  p(95)=19.2ms  
   ✓ http_req_failed................: 2.45%  ✓ 141      ✗ 5609
     http_req_receiving.............: avg=57.29µs min=10.73µs med=45.1µs  max=3.07ms   p(90)=93.86µs  p(95)=115.41µs
     http_req_sending...............: avg=59.15µs min=20.98µs med=42.66µs max=656.26µs p(90)=100.84µs p(95)=182.36µs
     http_req_tls_handshaking.......: avg=32.9µs  min=0s      med=0s      max=189.19ms p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=69.92ms min=2.25ms  med=13.15ms max=4.78s    p(90)=17.47ms  p(95)=20.82ms 
     http_reqs......................: 5750   9.523021/s
     iteration_duration.............: avg=5.22s   min=4.99s   med=5s      max=10.11s   p(90)=5s       p(95)=7.58s   
     iterations.....................: 115    0.19046/s
     vus............................: 0      min=0      max=1 
     vus_max........................: 1      min=0      max=1 
```
</details>

**Comment by austinborn** [comment]
I'll fix up the PR checks here

**Comment by cl-ea-js-service** [comment]
<details><summary>:heavy_check_mark: Soak test for coinmarketcap succeeded</summary>

```
default   [  98% ] 1 VUs  09m45.5s/10m0s

running (09m47.8s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m46.5s/10m0s

running (09m48.8s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m47.5s/10m0s

running (09m49.8s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m48.5s/10m0s

running (09m50.8s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m49.5s/10m0s

running (09m51.8s), 1/1 VUs, 112 complete and 0 interrupted iterations
default   [  98% ] 1 VUs  09m50.5s/10m0s

running (09m52.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m51.5s/10m0s

running (09m53.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m52.5s/10m0s

running (09m54.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m53.5s/10m0s

running (09m55.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m54.5s/10m0s

running (09m56.8s), 1/1 VUs, 113 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m55.5s/10m0s

running (09m57.8s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [  99% ] 1 VUs  09m56.5s/10m0s

running (09m58.8s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m57.5s/10m0s

running (09m59.8s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m58.5s/10m0s

running (10m00.8s), 1/1 VUs, 114 complete and 0 interrupted iterations
default   [ 100% ] 1 VUs  09m59.5s/10m0s

running (10m01.8s), 1/1 VUs, 114 complete and 0 interrupted iterations
default ↓ [ 100% ] 1 VUs  10m0s

running (10m02.8s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

running (10m03.8s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

running (10m03.8s), 0/1 VUs, 115 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  10m0s

     ✓ Group-coinmarketcap-AUDIO / USD returned 200
     ✗ Group-coinmarketcap-AMP / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-BAND / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-AAVE / ETH returned 200
      ↳  97% — ✓ 112 / ✗ 3
     ✗ Group-coinmarketcap-ALPHA / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-CAKE / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✓ Group-coinmarketcap-ALCX / ETH returned 200
     ✓ Group-coinmarketcap-ANT / ETH returned 200
     ✗ Group-coinmarketcap-COMP / ETH returned 200
      ↳  97% — ✓ 112 / ✗ 3
     ✗ Group-coinmarketcap-1INCH / ETH returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✗ Group-coinmarketcap-C98 / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✓ Group-coinmarketcap-AXS / ETH returned 200
     ✓ Group-coinmarketcap-APE / ETH returned 200
     ✓ Group-coinmarketcap-BAT / ETH returned 200
     ✓ Group-coinmarketcap-AAVE / USD returned 200
     ✓ Group-coinmarketcap-BNT / ETH returned 200
     ✓ Group-coinmarketcap-1INCH / USD returned 200
     ✗ Group-coinmarketcap-BNB / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-BNB / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-BAL / USD returned 200
      ↳  99% — ✓ 114 / ✗ 1
     ✓ Group-coinmarketcap-ALBT / USD returned 200
     ✗ Group-coinmarketcap-BAND / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✓ Group-coinmarketcap-COMP / USD returned 200
     ✓ Group-coinmarketcap-AMPL / ETH returned 200
     ✓ Group-coinmarketcap-ARPA / USD returned 200
     ✗ Group-coinmarketcap-ANKR / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-BIT / USD returned 200
      ↳  93% — ✓ 107 / ✗ 8
     ✗ Group-coinmarketcap-BTC / USD returned 200
      ↳  97% — ✓ 112 / ✗ 3
     ✓ Group-coinmarketcap-ATOM / USD returned 200
     ✓ Group-coinmarketcap-CELO / ETH returned 200
     ✓ Group-coinmarketcap-BTC / ETH returned 200
     ✗ Group-coinmarketcap-AMPL / USD returned 200
      ↳  96% — ✓ 111 / ✗ 4
     ✓ Group-coinmarketcap-ALCX / USD returned 200
     ✓ Group-coinmarketcap-ADX / USD returned 200
     ✓ Group-coinmarketcap-ATOM / ETH returned 200
     ✓ Group-coinmarketcap-BADGER / ETH returned 200
     ✗ Group-coinmarketcap-BUSD / ETH returned 200
      ↳  96% — ✓ 111 / ✗ 4
     ✗ Group-coinmarketcap-BORING / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-CRO / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✗ Group-coinmarketcap-BOND / ETH returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✓ Group-coinmarketcap-BAL / ETH returned 200
     ✓ Group-coinmarketcap-CREAM / ETH returned 200
     ✓ Group-coinmarketcap-AVAX / USD returned 200
     ✗ Group-coinmarketcap-APE / USD returned 200
      ↳  96% — ✓ 111 / ✗ 4
     ✗ Group-coinmarketcap-BADGER / USD returned 200
      ↳  96% — ✓ 111 / ✗ 4
     ✗ Group-coinmarketcap-ALUSD / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7
     ✓ Group-coinmarketcap-BUSD / USD returned 200
     ✓ Group-coinmarketcap-CEL / ETH returned 200
     ✓ Group-coinmarketcap-BNT / USD returned 200
     ✗ Group-coinmarketcap-ADA / USD returned 200
      ↳  93% — ✓ 108 / ✗ 7

     checks.........................: 97.68% ✓ 5617     ✗ 133 
     data_received..................: 1.7 MB 2.8 kB/s
     data_sent......................: 787 kB 1.3 kB/s
     errors.........................: 2.31%  ✓ 133      ✗ 5617
     http_req_blocked...............: avg=33.13µs min=97ns    med=227ns   max=188.69ms p(90)=324ns   p(95)=426ns   
     http_req_connecting............: avg=127ns   min=0s      med=0s      max=734.87µs p(90)=0s      p(95)=0s      
   ✓ http_req_duration..............: avg=68.88ms min=2.96ms  med=13.26ms max=2.9s     p(90)=17.93ms p(95)=21.54ms 
       { expected_response:true }...: avg=22.11ms min=4.55ms  med=13.22ms max=2.9s     p(90)=17.45ms p(95)=19.66ms 
   ✓ http_req_failed................: 2.31%  ✓ 133      ✗ 5617
     http_req_receiving.............: avg=65.39µs min=11.51µs med=43.08µs max=12.36ms  p(90)=97.76µs p(95)=125.9µs 
     http_req_sending...............: avg=59.1µs  min=21.71µs med=42.09µs max=7.19ms   p(90)=99.06µs p(95)=176.19µs
     http_req_tls_handshaking.......: avg=31.5µs  min=0s      med=0s      max=181.12ms p(90)=0s      p(95)=0s      
     http_req_waiting...............: avg=68.75ms min=2.89ms  med=13.15ms max=2.9s     p(90)=17.78ms p(95)=21.39ms 
     http_reqs......................: 5750   9.523105/s
     iteration_duration.............: avg=5.22s   min=4.99s   med=5s      max=10.11s   p(90)=5s      p(95)=7.57s   
     iterations.....................: 115    0.190462/s
     vus............................: 0      min=0      max=1 
     vus_max........................: 1      min=0      max=1 
```
</details>

**Review by austinborn — APPROVED** [review]

**Pull request merged**
