### PR TITLE
Bump framework version to 1.3.1

### PR DESCRIPTION
**Pull request by martin-cll**

### CODE REVIEW

**Comment by mxiao-cll** [comment]
Need a change set

Did you generate this by hand or via packages/scripts/src/framework/version-bump.sh ?

**Comment by martin-cll** [comment]
> Need a change set
> 
> Did you generate this by hand or via packages/scripts/src/framework/version-bump.sh ?

Added a changeset. I just find and replaced the versions in package.json files.

**Comment by austinborn** [comment]
@martin-cll for future reference you can also use this script to do the same thing (incl. the changeset): https://github.com/smartcontractkit/external-adapters-js/blob/main/packages/scripts/src/framework/version-bump.sh

**Review by mxiao-cll — APPROVED** [review]

**Comment by karen-stepanyan** [comment]
I am against merging this as it will break the github pipeline for Release (due to big amount of changes). Details are [here](https://smartcontract-it.atlassian.net/browse/DF-20336)

**Pull request closed without merging**
