### PR TITLE
Patch/PDI-179: Update coingecko-test framework version.

### PR DESCRIPTION
**Pull request by ad0ll**
Updates coingecko-test framework version from 0.11.x to 0.13.2

### CODE REVIEW

**Comment by cl-ea-js-service** [comment]
<details><summary>:warning: Soak test for coingecko-test failed :warning:</summary>

```
Flag --logformat has been deprecated, log-format

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io
```
</details>

<details><summary>:heavy_check_mark: </summary>

```
Applied:


Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```

```

</details>

**Comment by cl-ea-js-service** [comment]
<details><summary>:warning: Soak test for coingecko-test failed :warning:</summary>

```
Flag --logformat has been deprecated, log-format

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io
```
</details>

<details><summary>:heavy_check_mark: </summary>

```
Applied:


Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```

```

</details>

**Comment by cl-ea-js-service** [comment]
<details><summary>:warning: Soak test for coingecko-test failed :warning:</summary>

```
Flag --logformat has been deprecated, log-format

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io
```
</details>

<details><summary>:heavy_check_mark: </summary>

```
Applied:


Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```

```

</details>

**Comment by cl-ea-js-service** [comment]
<details><summary>:warning: Soak test for coingecko-test failed :warning:</summary>

```
Flag --logformat has been deprecated, log-format

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io
```
</details>

<details><summary>:heavy_check_mark: </summary>

```
Applied:


Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```

```

</details>

**Comment by cl-ea-js-service** [comment]
<details><summary>:warning: Soak test for coingecko-test failed :warning:</summary>

```
Flag --logformat has been deprecated, log-format

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io
```
</details>

<details><summary>:heavy_check_mark: </summary>

```
Applied:


Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```

```

</details>

**Review by alejoberardino — APPROVED** [review]

**Comment by cl-ea-js-service** [comment]
<details><summary>:warning: Soak test for coingecko-test failed :warning:</summary>

```
Flag --logformat has been deprecated, log-format

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io
```
</details>

<details><summary>:heavy_check_mark: </summary>

```
Applied:


Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```

```

</details>

**Comment by cl-ea-js-service** [comment]
<details><summary>:warning: Soak test for coingecko-test failed :warning:</summary>

```
Flag --logformat has been deprecated, log-format

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io
```
</details>

<details><summary>:heavy_check_mark: </summary>

```
Applied:


Failed:
(no failed assertions)
```

</details>

<details><summary>Output sample</summary>

```

```

</details>

**Comment by boxhock** [comment]
Didn't see this one before. I think we can maybe handle this in #2384

**Pull request closed without merging**
