### PR TITLE
Augur changes

### PR DESCRIPTION
**Pull request by boxhock**

### CODE REVIEW

**Comment by pgebheim** [comment]
@boxhock I believe this also needs the patch from d9fc73ade96eec7b5eeb252a58d376dabfb321e1

Which is a bug fix for skipping over a day

**Comment by boxhock** [comment]
@pgebheim This commit should have been cherry-picked in b387a2bec0d6b818ec0cc3090515f8a7be7dfb64. Has there been made changes outside the history of this PR?

**Comment by pgebheim** [comment]
Oh you're correct I missed that in the history.

**Comment by pgebheim** [comment]
Also, there is an additional API now available to just get the unresolved market ids from the contract.

https://github.com/AugurProject/turbo/blob/3fb7d91ed5147826d54c0908d158fb41236e08d8/packages/smart/contracts/turbo/AbstractMarketFactory.sol#L258

Perhaps this makes it easier to decided which markets to check against the api

**Pull request closed without merging**
