### PR TITLE
1forge websocket support

### PR DESCRIPTION
**Pull request by karen-stepanyan**
## Changes

added websocket support for 1forge EA

## Quality Assurance

- [ ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `<ADAPTER_PACKAGE>/schemas/env.json` and `<ADAPTER_PACKAGE>/README.md`
- [ ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `infra-k8s` configuration file.
- [ ] The branch naming follows git flow (`feature/x`, `chore/x`, `release/x`, `hotfix/x`, `fix/x`) or is created from Clubhouse/Shortcut
- [ ] This is related to a maximum of one Clubhouse/Shortcut story or GitHub issue
- [x] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)

### CODE REVIEW

**Comment by boxhock** [comment]
Need to create a changeset for this PR

**Comment by boxhock** [comment]
Running this locally, I get a ton of `WS: Message received with invalid format` messages in the logs. Do you know what's causing this? Is this something we can avoid? Is it breaking anything?

**Comment by karen-stepanyan** [comment]
> Running this locally, I get a ton of `WS: Message received with invalid format` messages in the logs. Do you know what's causing this? Is this something we can avoid? Is it breaking anything?

Websocket deserializer expected data to be JSON, so it parsed it. 1forge sends plain texts, that's why there were logs.

**Comment by boxhock** [comment]
@karen-stepanyan got it, thanks, looks good now!

**Review by boxhock — APPROVED** [review]

**Pull request merged**
