### PR TITLE
[Feat] SIP-237: Synthetix Debt Migrator

### PR DESCRIPTION
**Pull request by barrasso**
## Description

Updates the existing debt pool oracle code to account for the transfer of Synthetix debt shares (SDS) that have been migrated via the `DebtMigrator` (L1 -> L2 only).

The `chainTotalDebtShare` formula has changed to:

```
sum(SynthetixDebtShare.totalSupply() + DebtMigrator.debtTransferReceived() - DebtMigrator.debtTransferSent()) for all chains
```

*Note that the contract calls should be atomic or locked to a specific block on-chain.

## Changes

- [x] Add ABI & name helper for DebtMigrator
- [x] Modify total debt share formula to use DebtMigrator data

## Steps to Test

`yarn test packages/sources/synthetix-debt-pool/test/integration/adapter.test.ts`

## Quality Assurance

- [ ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `<ADAPTER_PACKAGE>/schemas/env.json` and `<ADAPTER_PACKAGE>/README.md`
- [ ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `infra-k8s` configuration file.
- [ ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `adapter-secrets` configuration file or update the [soak testing blacklist](/packages/scripts/src/get-changed-adapters/soakTestBlacklist.ts).
- [ ] If a new adapter was made, or a new endpoint was added, update the `test-payload.json` file with relevant requests.
- [x] The branch naming follows git flow (`feature/x`, `chore/x`, `release/x`, `hotfix/x`, `fix/x`) or is created from Clubhouse/Shortcut
- [ ] This is related to a maximum of one Clubhouse/Shortcut story or GitHub issue
- [x] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)
- [ ] All code changes have 100% unit and integration test coverage. If testing is not applicable or too difficult to justify doing, the reasoning should be documented explicitly in the PR.

### CODE REVIEW

**Comment by austinborn** [comment]
Hey @barrasso thanks for submitting this. Is the contract update already on all chains?

**Comment by barrasso** [comment]
> Hey @barrasso thanks for submitting this. Is the contract update already on all chains?

So far it's only deployed on goerli and OP-goerli. The plan is to deploy to mainnet by EoW.
I will reply back here when mainnet is complete.

**Comment by barrasso** [comment]
@austinborn took longer than expected, but the contracts are now live on Ethereum and Optimism mainnet as well.
This should be good to go

* `DebtMigratorOnEthereum`: https://etherscan.io/address/0x94f864e55c77E07C2C7BF7bFBc334b7a8123442A#code
* `DebtMigratorOnOptimism`: https://optimistic.etherscan.io/address/0xA6bc30d854c2647574921c4AF442008DB7d32ad5#code

**Comment by austinborn** [comment]
Looks like some of the integration tests are failing, likely because of missing mocks for ethers methods.:
```
Summary of all failing tests
FAIL packages/sources/synthetix-debt-pool/test/integration/adapter.test.ts (7.596 s)
  ● synthetix-debt-pool › debt-ratio › successfully fetches the debt ratio across all chains if chainSources is missing

    expected 200 "OK", got 500 "Internal Server Error"

      227 |         .set('Content-Type', 'application/json')
      228 |         .expect('Content-Type', /json/)
    > 229 |         .expect(200)
          |          ^
      230 |
      231 |       expect(response.body).toMatchSnapshot()
      232 |     })

      at Object.<anonymous> (packages/sources/synthetix-debt-pool/test/integration/adapter.test.ts:229:10)
      ----
      at Test._assertStatus (.yarn/cache/supertest-npm-6.2.4-6901daa695-f2ddc4f3ba.zip/node_modules/supertest/lib/test.js:252:14)
      at .yarn/cache/supertest-npm-6.2.4-6901daa695-f2ddc4f3ba.zip/node_modules/supertest/lib/test.js:306:17
      at Test._assertFunction (.yarn/cache/supertest-npm-6.2.4-6901daa695-f2ddc4f3ba.zip/node_modules/supertest/lib/test.js:285:13)
      at Test.assert (.yarn/cache/supertest-npm-6.2.4-6901daa695-f2ddc4f3ba.zip/node_modules/supertest/lib/test.js:164:23)
      at localAssert (.yarn/cache/supertest-npm-6.2.4-6901daa695-f2ddc4f3ba.zip/node_modules/supertest/lib/test.js:120:14)
      at fn (.yarn/cache/supertest-npm-6.2.4-6901daa695-f2ddc4f3ba.zip/node_modules/supertest/lib/test.js:125:7)
      at Test.callback (.yarn/cache/superagent-npm-8.0.0-23cfd5d736-14343e5932.zip/node_modules/superagent/src/node/index.js:924:3)
      at fn (.yarn/cache/superagent-npm-8.0.0-23cfd5d736-14343e5932.zip/node_modules/superagent/src/node/index.js:1153:18)
      at IncomingMessage.<anonymous> (.yarn/cache/superagent-npm-8.0.0-23cfd5d736-14343e5932.zip/node_modules/superagent/src/node/parsers/json.js:19:7)

  ● synthetix-debt-pool › debt-ratio › successfully fetches the debt ratio for only one chain

    expected 200 "OK", got 500 "Internal Server Error"

      246 |         .set('Content-Type', 'application/json')
      247 |         .expect('Content-Type', /json/)
    > 248 |         .expect(200)
          |          ^
      249 |
      250 |       expect(response.body).toMatchSnapshot()
      251 |     })

      at Object.<anonymous> (packages/sources/synthetix-debt-pool/test/integration/adapter.test.ts:248:10)
      ----
      at Test._assertStatus (.yarn/cache/supertest-npm-6.2.4-6901daa695-f2ddc4f3ba.zip/node_modules/supertest/lib/test.js:252:14)
      at .yarn/cache/supertest-npm-6.2.4-6901daa695-f2ddc4f3ba.zip/node_modules/supertest/lib/test.js:306:17
      at Test._assertFunction (.yarn/cache/supertest-npm-6.2.4-6901daa695-f2ddc4f3ba.zip/node_modules/supertest/lib/test.js:285:13)
      at Test.assert (.yarn/cache/supertest-npm-6.2.4-6901daa695-f2ddc4f3ba.zip/node_modules/supertest/lib/test.js:164:23)
      at localAssert (.yarn/cache/supertest-npm-6.2.4-6901daa695-f2ddc4f3ba.zip/node_modules/supertest/lib/test.js:120:14)
      at fn (.yarn/cache/supertest-npm-6.2.4-6901daa695-f2ddc4f3ba.zip/node_modules/supertest/lib/test.js:125:7)
      at Test.callback (.yarn/cache/superagent-npm-8.0.0-23cfd5d736-14343e5932.zip/node_modules/superagent/src/node/index.js:924:3)
      at fn (.yarn/cache/superagent-npm-8.0.0-23cfd5d736-14343e5932.zip/node_modules/superagent/src/node/index.js:1153:18)
      at IncomingMessage.<anonymous> (.yarn/cache/superagent-npm-8.0.0-23cfd5d736-14343e5932.zip/node_modules/superagent/src/node/parsers/json.js:19:7)
```
Can you make sure the [integration tests](https://github.com/smartcontractkit/external-adapters-js/blob/d8d2f78980aa44c8e722f90511b878ffdd630f43/packages/sources/synthetix-debt-pool/test/integration/adapter.test.ts#L65-L140) are updated to mock the new methods you've added? You can learn more about how to run our integration test suite [here](https://github.com/smartcontractkit/external-adapters-js/blob/develop/CONTRIBUTING.md#mock-integration-testing). `yarn setup && yarn test packages/sources/synthetix-debt-pool/test/integration/` with no RPC_URL variables set in your environment.

**Comment by barrasso** [comment]
@austinborn I added the missing mocks and the tests seem to be passing now 🚀

**Review by austinborn — APPROVED** [review]

**Pull request merged**
