### PR TITLE
Feature/sc 22208 - Add workflow and post-commit warning when adapter change is not accompanied by changeset

### PR DESCRIPTION
**Pull request by eddiejhong**
## Description
This change enforces the requirement that all adapter code changes be accompanied by a changeset by adding a failing CI step.

## Changes
* Add Github workflow which fails when a PR has an adapter change but does not include a changeset
* Add post-commit warning when a commit contains an adapter change but does not include a changeset

## Steps to Test
1. Pull down `feature/sc-22208` and check out a test branch
2. Add a commit to the test branch containing a change to a file in an adapter directory (packages/sources/*/src/* OR packages/composites/*/src/* OR packages/targets/*/src/*)
3. Observe that a post-commit warning appears "⚠️ NOTICE: Adapter changes must also have a changeset. Generate a changeset with 'yarn changeset' and include it in your commit."
4. Push the test branch to Github
5. Observe that the CI fails on step "Adapter changes accompanied by a changeset"

Example PR with failure: https://github.com/smartcontractkit/external-adapters-js/pull/1526

## Quality Assurance

- [x] Ran `yarn changeset` if adapter source code was changed
- [x] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `<ADAPTER_PACKAGE>/schemas/env.json` and `<ADAPTER_PACKAGE>/README.md`
- [x] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `infra-k8s` configuration file.
- [x] The branch naming follows git flow (`feature/x`, `chore/x`, `release/x`, `hotfix/x`, `fix/x`) or is created from Clubhouse/Shortcut
- [x] This is related to a maximum of one Clubhouse/Shortcut story or GitHub issue
- [x] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)

### CODE REVIEW

**Comment by eddiejhong** [comment]
This change allows us to remove the more permissive changeset-bot from our PR workflow

**Review by alejoberardino — CHANGES_REQUESTED** [review]
The script that's run in the GitHub action is not that short, and it's very similar to the one in the commit hook; I think a good improvement would be to have it as a separate script file and call that one from the other places. Beyond that, I'm all for this change

**Comment by eddiejhong** [comment]
> The script that's run in the GitHub action is not that short, and it's very similar to the one in the commit hook; I think a good improvement would be to have it as a separate script file and call that one from the other places. Beyond that, I'm all for this change

Yes, I agree that I should abstract that logic into a separate script. I'll see if I can refactor that code so that I'm not repeating myself!

**Review by alejoberardino — APPROVED** [review]

**Review by justinkaseman — APPROVED** [review]
Nice!

**Pull request merged**
