### PR TITLE
Add generalized NFT API

### PR DESCRIPTION
**Pull request by 0xJPEG**
## Description

Adds generalized `/collections` endpoint that can be used to query any NFT collection, including those already supported by the `/punks` endpoint. 

## Changes

- Added new endpoint
- Added tests for new endpoint

## Steps to Test

1. Run tests
2. Run node with provided API keys

## Quality Assurance

- [x] Ran `yarn changeset` if adapter source code was changed
- [x] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `<ADAPTER_PACKAGE>/schemas/env.json` and `<ADAPTER_PACKAGE>/README.md`
- [x] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `infra-k8s` configuration file.
- [x] The branch naming follows git flow (`feature/x`, `chore/x`, `release/x`, `hotfix/x`, `fix/x`) or is created from Clubhouse/Shortcut
- [x] This is related to a maximum of one Clubhouse/Shortcut story or GitHub issue
- [x] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)

### CODE REVIEW

**Review by austinborn — APPROVED** [review]
Looks great, just needed to make adjustments for the schema file (we only use it for adapter env vars, so it doesn't need the `collection` info).

**Comment by austinborn** [comment]
@0xJPEG Can you re-sync your forked `develop` branch with `smartcontractkit:develop` and resolve the merge conflicts here?

**Comment by austinborn** [comment]
Once the conflicts have been resolved, I'll be happy to approve it!

**Comment by 0xJPEG** [comment]
Thanks, I'll take a look at those tests and ping when ready

**Comment by austinborn** [comment]
For the integration test it looks like you just need to update the snapshot:
``` yarn test packages/sources/jpegd/test/integration/* --updateSnapshot```
And for the unit test, if you can't figure it out feel free to just have a single test or look at others for examples. The unit test framework we have isn't great right, so the tests don't provide much value right now...

**Comment by 0xJPEG** [comment]
Think we're good? @austinborn

**Review by austinborn — APPROVED** [review]

**Pull request merged**
