### PR TITLE
[DO NOT MERGE] Remove unused adapters

### PR DESCRIPTION
**Pull request by alejoberardino**
Adapters removed: 

- accuweather
- agoric
- alpine
- anchor
- augur
- binance-dex
- bob
- bsol-price
- cache.gold
- ccip-read
- circuit-breaker
- coincodex
- conflux
- crypto-volatility-index
- cryptoapis-v2
- deribit
- dns-query
- dns-record-check
- dwolla
- dydx-rewards
- expert-car-broker
- flightaware
- geodb
- google-bigquery
- google-weather
- graphql
- harmony
- ipfs
- market-closure
- marketstack
- messari
- paypal
- reference-transform
- spectral-macro-score
- terra-view-function
- the-graph
- therundown
- uniswap-v3

### CODE REVIEW

**Comment by austinborn** [comment]
Can we get secondary approval from @nikhsha before this goes in?

**Comment by alejoberardino** [comment]
> Can we get secondary approval from @nikhsha before this goes in?

For sure, this is just a test PR on my end to see that all tests & CI run smoothly, I'll be sending this list out for others to approve before this is merged

**Comment by alejoberardino** [comment]
Blocking this until we write down clear expectations for these EAs

**Review by austinborn — DISMISSED** [review]

**Comment by mxiao-cll** [comment]
Please re-open if still relevant

**Pull request closed without merging**
