### PR TITLE
Add stMATIC External Adapter token Price Feed

### PR DESCRIPTION
**Pull request by idirall22**
## Description
External adapter for **stMATIC** token price feed.

Lido on Polygon is a DAO governed liquid staking protocol for the Polygon PoS chain. It allows users to stake their ERC20 MATIC tokens on the Ethereum mainnet and immediately get the representation of their share in the form of a stMATIC token without maintaining staking infrastructure. Users will get staking rewards and still be able to control their stMATIC tokens MATIC tokens will be delegated across validators that are registered and accepted by the DAO insideLido on the Polygon protocol.
The goal is to help with Polygon decentralization and integrate stMATIC with the variety of protocols and Defi applications on the Ethereum mainnet and Polygon PoS chain.

- [Github](https://github.com/Shard-Labs/PoLido)
- [Documentation](https://docs.polygon.lido.fi/)
- [Dapp](https://polygon.lido.fi/)
- [Twitter](https://twitter.com/LidoOnPolygon)

## Changes
New!!
Implemented stMatic price feed adapter. The adapter use on chain data to calculate the stMatic price
- [MATIC <> USD] price (https://polygonscan.com/address/0xAB594600376Ec9fD91F8e885dADF0CE036862dE0#readContract)
- [MATIC <> stMATIC] ratio (https://polygonscan.com/address/0xdEd6C522d803E35f65318a9a4d7333a22d582199#readContract)

## Steps to Test
1. Run `yarn test stmatic/test/unit`

## Quality Assurance

- [ ] Ran `yarn changeset` if adapter source code was changed
- [x] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `<ADAPTER_PACKAGE>/schemas/env.json` and `<ADAPTER_PACKAGE>/README.md`
- [ ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `infra-k8s` configuration file.
- [ ] The branch naming follows git flow (`feature/x`, `chore/x`, `release/x`, `hotfix/x`, `fix/x`) or is created from Clubhouse/Shortcut
- [ ] This is related to a maximum of one Clubhouse/Shortcut story or GitHub issue
- [x] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)

### CODE REVIEW

**Comment by austinborn** [comment]
@idirall22 Could you pull in some changes I added in a commit (86c39b7a) to the `feature/lido` branch? It should just be a single commit on top of the latest from this PR branch, which includes the following changes:
- Use the `Requester.success` method for the response
- Naming conventions for the adapter and endpoint
- Integration tests
- Update other metadata files that are used in our CI/CD process

Once I have these changes in I will be able to run the PR checks to make sure it looks good, approve, and merge it in.

**Comment by idirall22** [comment]
HEy @austinborn !
Thanks for your support :)
I included your your commit (https://github.com/smartcontractkit/external-adapters-js/commit/86c39b7ab6445b39bb625bb4b28dd06afd1a4210)
Let's me know if I have to do anything else

**Comment by austinborn** [comment]
@idirall22 to cut back on the number of changed cache files, I re-did the commit change and also merged the latest from this `develop` into it as well. Can you remove that last commit and push a047d0f4f1 instead?

**Review by austinborn — APPROVED** [review]
Great work! If you have any suggestions on how we can improve the external contributor process, please let us know.

**Pull request merged**
