### PR TITLE
Add external adapter for lido on Kusama liquid token (stKSM/USD)

### PR DESCRIPTION
**Pull request by DZahar0v**
## Description

......

## Changes

- High level
- changes that
- you made

## Steps to Test

1. Steps
2. to
3. test

## Quality Assurance

- [ ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `<ADAPTER_PACKAGE>/schemas/env.json` and `<ADAPTER_PACKAGE>/README.md`
- [ ] If a new adapter was made, or an existing one was modified so that its environment variables have changed, update the relevant `infra-k8s` configuration file.
- [ ] The branch naming follows git flow (`feature/x`, `chore/x`, `release/x`, `hotfix/x`, `fix/x`) or is created from Clubhouse/Shortcut
- [ ] This is related to a maximum of one Clubhouse/Shortcut story or GitHub issue
- [ ] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)
- [ ] All code changes have 100% unit and integration test coverage. If testing is not applicable or too difficult to justify doing, the reasoning should be documented explicitly in the PR.

### CODE REVIEW

**Review by justinkaseman — CHANGES_REQUESTED** [review]
Hey @DZahar0v! Appreciate the contribution to our mono-repo.

We keep all our our External Adapters using our EA framework & tooling.
See the contribution guide [here](https://github.com/smartcontractkit/external-adapters-js/blob/develop/CONTRIBUTING.md) for some guidelines how how to get this PR approved.

Happy to answer any questions that come up.

**Comment by DZahar0v** [comment]
@justinkaseman Hi! Thanks for your early reply. We've fixed our stKSM adapter according to the rules presented [here](https://github.com/smartcontractkit/external-adapters-js/blob/develop/CONTRIBUTING.md). Make a new review, please.

**Comment by DZahar0v** [comment]
@justinkaseman Hi! We've updated our external adapter, so now it calculates price according to this formula stKSM_price = KSM_price * total_KSM_in_Lido / total_stKSM_supply

**Comment by justinkaseman** [comment]
Hey @DZahar0v, apologies for the lack of a reply. This got lost in the shuffle of the EAv3 framework.
Is this adapter still one that you would like to get merged? Or can this PR be closed?

**Comment by justinkaseman** [comment]
Closing as stale, feel free to re-open

**Pull request closed without merging**
